name: neutrapro
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pip
  # Deep Learning Framework
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.3  # Adjust based on your CUDA version
  
  # Data Processing and Analysis
  - pandas>=1.3.0
  - numpy>=1.21.0
  - h5py>=3.1.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Utilities
  - tqdm>=4.62.0
  
  # Bioinformatics (from bioconda)
  - biopython>=1.79
  
  # pip dependencies (packages not available via conda)
  - pip:
    - transformers>=4.20.0
    - biomart>=0.9.2
    - mygene>=3.2.2